spring.datasource.url=jdbc:mysql://localhost:3306/jobPulse_db
spring.datasource.username=root
spring.datasource.password=pass

SecretJwtString=yzSh2J2ieRbvwCayyO5pK63640yKJzKrlSn7hXOH0d4H9cE9lrssQSCPk53EsjUWec4527Vl7896IoUeMhTC+A==

encryption.secret-key=JobPulseAESKey32ByteSecretString12

ai.api.key=oc_sk_188429f9c47c_G3KtkJdtDXHMCkGi-fSmEN2qvtWkODBA
ai.api.base-url=https://console.opencode.ai/inference/openai/v1
ai.api.model=mimo-v2.5-free

app.frontend.url=http://localhost:5173
